use_gpu: True
device: 0
early_stop:
  patience: 0

federate:
  mode: standalone
  client_num: 53
  sample_client_num: -1         # ← 매 라운드 전 클라이언트 참여
  total_round_num: 1 # CT-FT: 1라운드 파인튜닝
  save_to: ""     # 빈 문자열(또는 null)로 두면 경로가 없어 저장 안 함
  save_freq: 0    # 0이면 주기 저장 비활성화
  ignore_weight: True
  share_local_model: True
  online_aggr: False
data:
  root: data/
  type: 'reddit-tldr-comparison-choice@llm'
  splits: [0.9,0.09,0.01]
  splitter: 'meta'
llm:
  tok_len: 1024
  accelerator:
    use: True
  chat:
    max_len: 1024
  adapter:
    use: True
    count: 10
    warmup:
      use: True
      round: 25
    grouping:
      use: True
      round: 250
    args: [ { 'adapter_package': 'peft', 'adapter_method': 'lora', 'r': 8, 'lora_alpha': 16, 'lora_dropout': 0.05, target_modules: [ "q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj" ] } ]
  # reward_coeff: 0.1
  grad_accum_step: 2
dataloader:
  batch_size: 2
model:
  type: 'Qwen/Qwen2-0.5B@huggingface_llm'
train:
  local_update_steps: 100 # 클라이언트당 optimizer step 기준 업데이트 횟수
  batch_or_epoch: batch
  optimizer:
    # type: RMSprop
    # lr: 0.000001
    type: AdamW
    betas: (0.9, 0.95)
    lr: 0.00001
  is_enable_half: True # bf16/half 사용 플래그(Accelerate가 처리)

criterion:
  type: CrossEntropyLoss
trainer:
  type: llmrewardchoicetrainer
  choices: ['A', 'B']
eval:
  freq: 300
  split: ['val', 'test']
  metrics: ['loss', 'acc']
  best_res_update_round_wise_key: test_loss
  count_flops: False
outdir: exp/tldr/choice_qwen/fedbiscuit_u10_warmup_1.0
expname: ""