use_gpu: True
device: 0
early_stop:
  patience: 0

federate:
  mode: standalone
  client_num: 53
  sample_client_num: -1         # ← 매 라운드 전 클라이언트 참여
  total_round_num: 1 # CT-FT: 1라운드 파인튜닝
  ignore_weight: True
  share_local_model: True
  online_aggr: False
data:
  root: data/
  type: 'reddit-tldr-comparison-choice@llm'
  splits: [0.9,0.09,0.01]
  splitter: 'meta'
llm:
  tok_len: 1024
  accelerator:
    use: True
  chat:
    max_len: 1024
  adapter:
    balance: False
    use: True
    count: 3
    grouping:
      use: True
      round: 0
    args: [ { 'adapter_package': 'peft', 'adapter_method': 'lora', 'r': 8, 'lora_alpha': 16, 'lora_dropout': 0.05, target_modules: [ "q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj" ] } ]
  # reward_coeff: 0.1
  grad_accum_step: 2
dataloader:
  batch_size: 2
model:
  type: 'Qwen/Qwen2-0.5B@huggingface_llm'
  load_from_local_pretrained_model_path: 'checkpoints_1.0/final_tldr_choice_qwen_fedbiscuit_u3_plain_round_175.ckpt'
train:
  local_update_steps: 100 # 클라이언트당 optimizer step 기준 업데이트 횟수
  batch_or_epoch: batch
  optimizer:
    # type: RMSprop
    # lr: 0.000001
    type: AdamW
    betas: (0.9, 0.95)
    lr: 0.00001
  is_enable_half: True # bf16/half 사용 플래그(Accelerate가 처리)

criterion:
  type: CrossEntropyLoss

trainer:
  type: llmrewardchoicetrainer
  choices: ['A', 'B']

eval:
  split: ['val', 'test']
  metrics: ['loss', 'acc']
  count_flops: False
  outdir: exp/tldr/choice_qwen/pfl/fedbiscuit_u3_1.0/plain_plain/raw  # raw 로그 저장 루트
  # CT-FT(1라운드)에서 mid-eval 스텝 단위로 기록 (train/eval 모두 raw로 남김)
  every_n_train_steps: 10       # 10, 20, 30스텝에 mid-eval + train 스냅샷 기록
  baseline_before_ft: True      # 파인튜닝 시작 전(step=0) 베이스라인 기록


outdir: exp/tldr/choice_qwen/pfl/fedbiscuit_u3_1.0/plain_plain
expname: ""