use_gpu: True
device: 0
early_stop:
  patience: 0
federate:
  mode: standalone
  client_num: 53
  sample_client_num: 5
  total_round_num: 175
  save_to: "checkpoints_1.0/tldr_choice_qwen_fedbiscuit_u10_plain.ckpt"
  ignore_weight: True
  save_freq: 25
  share_local_model: True
  online_aggr: False
data:
  root: data/
  type: 'reddit-tldr-comparison-choice@llm'
  splits: [0.9,0.09,0.01]
  splitter: 'meta'
llm:
  tok_len: 1024
  accelerator:
    use: True
  chat:
    max_len: 1024
  adapter:
    balance: False
    use: True
    count: 10
    warmup:
      use: True
      round: 0
    grouping:
      use: True
      round: 25
    args: [ { 'adapter_package': 'peft', 'adapter_method': 'lora', 'r': 8, 'lora_alpha': 16, 'lora_dropout': 0.05, target_modules: [ "q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj" ] } ]
  # reward_coeff: 0.1
  grad_accum_step: 2
dataloader:
  batch_size: 2
model:
  type: 'Qwen/Qwen2-0.5B@huggingface_llm'
  load_from_local_pretrained_model_path: 'checkpoints_u10_warmup_1.0/final_tldr_choice_qwen_fedbiscuit_u10_warmup_1.0_round_250.ckpt'
train:
  local_update_steps: 30
  batch_or_epoch: batch
  optimizer:
    # type: RMSprop
    # lr: 0.000001
    type: AdamW
    betas: (0.9, 0.95)
    lr: 0.00001
  scheduler:
    milestones: [75, 125]    # 75라운드, 125라운드에 감축
    gamma: 1.0            # ×1.0씩 곱해 감축
  is_enable_half: True
criterion:
  type: CrossEntropyLoss
trainer:
  type: llmrewardchoicetrainer
  choices: ['A', 'B']
eval:
  freq: 25
  split: ['val', 'test']
  metrics: ['loss', 'acc']
  best_res_update_round_wise_key: test_loss
  count_flops: False
outdir: exp/tldr/choice_qwen/gfl/fedbiscuit_u10_1.0_plain
expname: ""