use_gpu: True
device: 0
early_stop:
  patience: 0
federate:
  mode: standalone
  sampler: cluster
  client_num: 35
  sample_client_num: 5
  total_round_num: 0
  save_to: "checkpoints_1.0_oracle/tldr_choice_qwen_fedbis_oracle_u3.ckpt"
  ignore_weight: True
  save_freq: 100
  share_local_model: True
  online_aggr: False
data:
  root: data/
  type: 'reddit-tldr-comparison-choice@llm'
  splits: [0.9,0.09,0.01]
  splitter: 'meta'
llm:
  tok_len: 1024
  accelerator:
    use: True
  chat:
    max_len: 1024
  adapter:
    use: True
    count: 3
    clusters_file: fedbiscuit_script/tldr/clusters_u3_53.json
    round_budget: 200
    target_per_round: 5
    warmup:
      use: True
      round: 0
    grouping:
      use: False
    args: [ { 'adapter_package': 'peft', 'adapter_method': 'lora', 'r': 8, 'lora_alpha': 16, 'lora_dropout': 0.05, target_modules: [ "q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj" ] } ]
  # reward_coeff: 0.1
  grad_accum_step: 2
dataloader:
  batch_size: 2
model:
  type: 'Qwen/Qwen2-0.5B@huggingface_llm'
train:
  local_update_steps: 30
  batch_or_epoch: batch
  optimizer:
    # type: RMSprop
    # lr: 0.000001
    type: AdamW
    betas: (0.9, 0.95)
    lr: 0.00001
  scheduler:
    milestones: [75, 125]    # 75라운드, 125라운드에 감축
    gamma: 1.0            # ×1.0씩 곱해 감축
  is_enable_half: True
criterion:
  type: CrossEntropyLoss
trainer:
  type: llmrewardchoicetrainer
  choices: ['A', 'B']
eval:
  freq: 500
  split: ['val', 'test']
  metrics: ['loss', 'acc']
  best_res_update_round_wise_key: test_loss
  count_flops: False
outdir: exp/tldr/choice_qwen/gfl/fedbis_oracle_u3_1.0
expname: ""