use_gpu: True
device: 3
early_stop:
  patience: 0
federate:
  mode: standalone
  client_num: 3
  total_round_num: 1000
  save_to: "checkpoints/llama.gsm.offsite_tuning.fr12_adpt4.lr50.fl.ckpt"
  save_freq: 500
  share_local_model: True
  online_aggr: False
data:
  root: data/
  type: 'gsm8k@llm'
  splits: [0.998,0.001,0.001]
  splitter: 'iid'
llm:
  tok_len: 1000
  chat:
    max_len: 1000
  offsite_tuning:
    use: True
    emu_r: 12
    strategy: 'noname'
    kwargs: [ { 'adapter_size': 4 }]
dataloader:
  batch_size: 1
model:
  type: 'decapoda-research/llama-7b-hf@huggingface_llm'
train:
  local_update_steps: 30
  batch_or_epoch: batch
  optimizer:
    lr: 0.005
  is_enable_half: True
criterion:
  type: CrossEntropyLoss
trainer:
  type: llmtrainer
eval:
  freq: 100
  metrics: ['loss']
  best_res_update_round_wise_key: 'val_loss'
  report: ['weighted_avg', 'avg', 'raw']
expname: "fl-llm/llama-7b_gsm8k_offsite-tuning_fr12-adpt4"
# wandb:
#   use: True
#   name_user: 'harliwu'
#   name_project: 'llama-7b_gsm8k_offsite-tuning'